FROM maven:latest

WORKDIR /code

COPY . /code

ARG DB_HOST
ARG DB_PASSWORD
ARG DB_USERNAME
ARG DB_NAME
ARG JWT_SECRET
ARG TEST_ADMIN_ACCOUNT_EMAIL
ARG TEST_ADMIN_ACCOUNT_PASSWORD
ARG TEST_EMPLOYEE_ACCOUNT_EMAIL
ARG TEST_EMPLOYEE_ACCOUNT_PASSWORD

ENV DB_HOST ${DB_HOST}
ENV DB_PASSWORD ${DB_PASSWORD}
ENV DB_USERNAME ${DB_USERNAME}
ENV DB_NAME ${DB_NAME}
ENV JWT_SECRET ${JWT_SECRET}
ENV TEST_ADMIN_ACCOUNT_EMAIL ${TEST_ADMIN_ACCOUNT_EMAIL}
ENV TEST_ADMIN_ACCOUNT_PASSWORD ${TEST_ADMIN_ACCOUNT_PASSWORD}
ENV TEST_EMPLOYEE_ACCOUNT_EMAIL ${TEST_EMPLOYEE_ACCOUNT_EMAIL}
ENV TEST_EMPLOYEE_ACCOUNT_PASSWORD ${TEST_EMPLOYEE_ACCOUNT_PASSWORD}

RUN mvn clean install -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "/code/target/DropwizardWebService-1.0-SNAPSHOT.jar", "server", "/code/config.yml"]
