INSERT INTO role (role_name) VALUES
    ('admin'),
    ('employee');

INSERT INTO user (email, role_id, salt, secured_password) VALUES
    ('Admin123@email.com', 1, 'qwertyui', '062742bd7303fd97dc3e059dc3595e97114ae28815901c518b9a4e283e9512f6'),
    ('Employee123@email.com', 2, 'asdfghjk', '79fb350ff31e939d2b5d4b8ed498e2ec6782eed7943e943d29e40c6e4fbd077d');

-- Insert statements for the job roles table
INSERT INTO job_role (job_role_name) VALUES
    ('Innovation Lead'),
    ('Technology Leader'),
    ('Software Engineer'),
    ('Software Engineer'),
    ('Support Technician'),
    ('Front-End Engineer'),
    ('Software Engineer'),
    ('Senior Support Technician'),
    ('Senior Front-End Engineer'),
    ('Senior Software Engineer'),
    ('Lead Managed Services Engineer'),
    ('Lead Software Engineer'),
    ('Technical Architect'),
    ('Solution Architect'),
    ('Dynamics 365 / Power Platform Solution Architect'),
    ('Principal Architect'),
    ('Test Engineer'),
    ('Test Engineer'),
    ('Senior NFT Engineer'),
    ('Senior Test Engineer'),
    ('Test Manager'),
    ('Lead NFT Engineer'),
    ('Lead Test Engineer'),
    ('Test Architect'),
    ('Principal Test Architect'),
    ('Product Specialist'),
    ('Senior Product Specialist'),
    ('Lead Product Specialist'),
    ('Intelligent Automation Solution Architect'),
    ('Low Code Engineer'),
    ('Low Code Engineer'),
    ('Low Code Principal Architect'),
    ('Head of Cloud Practice'),
    ('Lead Platform Engineer'),
    ('Senior Platform Engineer'),
    ('Platform Engineer'),
    ('Trainee Platform Engineer'),
    ('Principal Architect'),
    ('Solution Architect'),
    ('Technical Architect'),
    ('Senior Technical Specialist'),
    ('Cloud Economist'),
    ('Technical Specialist'),
    ('Cloud Migration Architect'),
    ('Cloud Migration Lead'),
    ('Head of IT Operations'),
    ('Systems Operations Manager'),
    ('Service Category Lead'),
    ('Lead Systems Support Engineer'),
    ('Service Category Lead'),
    ('Senior Systems Support Engineer'),
    ('Systems Support Engineer'),
    ('Trainee Systems Support Engineer'),
    ('Senior Systems Support Engineer'),
    ('Systems Support Engineer'),
    ('Trainee Systems Support Engineer'),
    ('Data Solution Architect'),
    ('Lead Data Technical Architect'),
    ('Lead Data Engineer'),
    ('Senior Data Engineer'),
    ('Data Engineer'),
    ('Trainee Data Engineer'),
    ('Principal Architect (Data and AI)'),
    ('Data Architect'),
    ('Data Architect'),
    ('AI Engineering Manager'),
    ('Lead AI Engineer'),
    ('Senior AI Engineer'),
    ('Associate AI Engineer'),
    ('Trainee AI Engineer'),
    ('Data Science Manager'),
    ('Consultant Data Scientist'),
    ('Senior Data Scientist'),
    ('Associate Data Scientist'),
    ('Trainee Data Scientist'),
    ('Principal Data and AI Consultant'),
    ('Data Consultant'),
    ('Data Consultant'),
    ('Data Migration Architect'),
    ('Data Analytics Manager'),
    ('Lead Data Analyst'),
    ('Senior Data Analyst'),
    ('Data Analyst'),
    ('Trainee Data Analyst'),
    ('Security Engineer'),
    ('Security Engineer'),
    ('Senior Security Engineer'),
    ('Security Architect, Lead Security Engineer'),
    ('Senior Security Architect'),
    ('Principal Security Architect'),
    ('Cyber Risk Assessor'),
    ('Security Analyst'),
    ('Senior Security Analyst'),
    ('Lead Security Analyst'),
    ('Corporate Security Manager'),
    ('Workday Practice Strategy and Planning Delivery Director'),
    ('HCM Solution Architect'),
    ('HCM Consultant'),
    ('HCM Consultant'),
    ('HCM Consultant'),
    ('HCM Consultant'),
    ('HCM Consultant'),
    ('Financials Solution Architect'),
    ('Financials Consultant'),
    ('Financials Consultant'),
    ('Financials Consultant'),
    ('Financials Consultant'),
    ('Financials Consultant'),
    ('Financials Consultant'),
    ('Data Solution Architect'),
    ('Data Consultant'),
    ('Data Consultant'),
    ('Data Consultant'),
    ('Data Consultant'),
    ('Data Consultant'),
    ('Integrations Solution Architect'),
    ('Integrations Consultant'),
    ('Integrations Consultant'),
    ('Integrations Consultant'),
    ('Integrations Consultant'),
    ('Integrations Consultant'),
    ('Head of Change and User Adoption'),
    ('Change and User Adoption Solution Architect'),
    ('Change and User Adoption Consultant'),
    ('Change and User Adoption Consultant'),
    ('Change and User Adoption Consultant'),
    ('Change and User Adoption Consultant'),
    ('Change and User Adoption Consultant'),
    ('Adaptive Planning Solution Architect'),
    ('Adaptive Planning Solution Architect'),
    ('Adaptive Planning Consultant'),
    ('Adaptive Planning Consultant'),
    ('Adaptive Planning Consultant'),
    ('Head of Customer Engagement - Products'),
    ('Delivery Director'),
    ('Principal Test Manager'),
    ('Technical Lead'),
    ('Test Manager'),
    ('Test Consultant'),
    ('Test Consultant'),
    ('Test Consultant'),
    ('Test Consultant'),
    ('Principal Product Manager'),
    ('Product Manager'),
    ('Product Owner'),
    ('Product Marketing Consultant'),
    ('Product Owner'),
    ('Business Analyst'),
    ('Workday Extend Principal Architect'),
    ('Workday Extend Architect'),
    ('Workday Extend Architect'),
    ('Workday Extend Developer'),
    ('Workday Extend Developer'),
    ('Workday Extend Trainee'),
    ('Service Delivery Principal'),
    ('Advisory Principal'),
    ('Service Delivery Manager'),
    ('Advisory Manager'),
    ('Service Delivery Consultant'),
    ('Service Delivery Senior Associate'),
    ('Service Delivery Associate'),
    ('Service Delivery Associate'),
    ('User Researcher'),
    ('User Researcher'),
    ('User Researcher'),
    ('User Researcher'),
    ('User Researcher Lead'),
    ('Experience Design Principal'),
    ('Chief Design Officer'),
    ('Content Designer'),
    ('Content Designer'),
    ('Content Designer Lead'),
    ('Experience Design Principal'),
    ('Chief Design Officer'),
    ('UX Designer'),
    ('UX Designer'),
    ('UX Designer'),
    ('UX Designer'),
    ('UX Design Lead'),
    ('Experience Design Principal'),
    ('Chief Design Officer'),
    ('Service Designer'),
    ('Experience Strategy Lead'),
    ('Service Design Lead'),
    ('Experience Design Principal'),
    ('Chief Design Officer'),
    ('Product Consultant'),
    ('Product Consultant'),
    ('Product Consultant'),
    ('Product Consultant'),
    ('Product Consultant'),
    ('Product Consultant'),
    ('Digital Advisory Consultant'),
    ('Digital Advisory Consultant'),
    ('Digital Advisory Consultant'),
    ('Digital Advisory Consultant'),
    ('Low Code Consultant'),
    ('Low Code Consultant'),
    ('Low Code Consultant'),
    ('Low Code Consultant'),
    ('Low Code Consultant'),
    ('Low Code Consultant'),
    ('Delivery Lead'),
    ('Principal Delivery Manager'),
    ('Programme Manager'),
    ('Delivery Manager'),
    ('Engagement Manager'),
    ('Senior Agility Coach'),
    ('Team Lead'),
    ('Engagement Manager'),
    ('Agile Coach'),
    ('Delivery Manager'),
    ('Agile Practitioner'),
    ('Principal Engineering Manager'),
    ('Principal Service Manager'),
    ('Senior Service Manager'),
    ('Service Manager'),
    ('Service Lead'),
    ('Engagement Manager'),
    ('Engagement Manager'),
    ('Engagement Manager'),
    ('Engagement Manager'),
    ('Engagement Manager'),
    ('Programme Office Lead'),
    ('Programme Office Assistant'),
    ('Programme Office Assistant'),
    ('Programme Office Assistant'),
    ('Director of Operations'),
    ('Financial Operations Analyst'),
    ('Operations Manager'),
    ('Operations Manager'),
    ('Head of Operations'),
    ('Staffing Consultant'),
    ('Staffing Consultant'),
    ('Staffing and PMO Lead'),
    ('Global Head of Marketing'),
    ('Business Development Lead'),
    ('Account Lead'),
    ('Business Development Associate'),
    ('Senior Business Development Associate'),
    ('Business Development Consultant'),
    ('Business Development Manager'),
    ('Business Development Director'),
    ('Customer Success Associate'),
    ('Customer Success Consultant'),
    ('Customer Success Manager'),
    ('Customer Success Manager'),
    ('Customer Success Director'),
    ('Cloud Partner Operations Manager'),
    ('Partners Consultant'),
    ('Partners Relationship Manager'),
    ('Partners Director'),
    ('Senior Bid Production Associate'),
    ('Technical Pre-Sales Consultant'),
    ('Big Production Consultant'),
    ('Big Production Manager'),
    ('Big Production Director/Head of Product Presales'),
    ('Sales Development Representative'),
    ('Senior Sales Development Representative'),
    ('Sales Development Consultant'),
    ('Sales Development Manager'),
    ('Product Demand Generation Director'),
    ('Marketing Assistant'),
    ('Marketing Associate'),
    ('Marketing Executive'),
    ('Senior Marketing Executive'),
    ('Marketing Manager'),
    ('Marketing Director'),
    ('Martech and Ops Assistant'),
    ('Martech and Ops Associate'),
    ('Martech and Ops Executive'),
    ('Senior Martech and Ops Executive'),
    ('Marketing Operations Manager'),
    ('Digital Strategy Manager'),
    ('Digital Strategy Director'),
    ('Head of Practice'),
    ('Head of Quality and Compliance'),
    ('Chief Information Officer (CIO)'),
    ('Regional/Sector Lead'),
    ('Head of Planning and Strategic Initiatives'),
    ('Practice Lead'),
    ('Chief AI Officer'),
    ('Chief Executive Officer (CEO)'),
    ('Chief Financial Officer (CFO)'),
    ('Chief People Officer (CPO)'),
    ('Investor Relations'),
    ('Director of Innovation'),
    ('Business Unit (BU) Head'),
    ('BU Chief Operating Officer (COO)'),
    ('Vice President of Business Development'),
    ('Workday Practice Director of Product'),
    ('Regional/Sector Director'),
    ('Chief Revenue Officer'),
    ('Head of Strategic Partnering'),
    ('People Principal'),
    ('People Operations Manager'),
    ('People Operations Consultant'),
    ('Senior People Operations Associate'),
    ('People Operations Associate'),
    ('People Operations Trainee'),
    ('Head of Organisational Development & Learning'),
    ('Talent Development & Learning Principal'),
    ('Organisational Development & Learning Manager'),
    ('Internal Communications Manager'),
    ('Organisational Development & Learning Consultant'),
    ('Entry Level Partner'),
    ('Senior Organisational Development & Learning Associate'),
    ('Organisational Development & Learning Associate'),
    ('Global Head of Talent Acquisition'),
    ('Head of Talent Acquisition'),
    ('Talent Acquisition Manager'),
    ('Talent Acquisition Lead'),
    ('Talent Acquisition Partner'),
    ('Talent Acquisition Specialist'),
    ('Global Head of Commercial'),
    ('Group Head of Finance'),
    ('Senior Commercial Associate'),
    ('Commercial Consultant'),
    ('Commercial Manager'),
    ('Senior Commercial Manager'),
    ('Finance Trainee'),
    ('Finance Associate'),
    ('Senior Finance Associate'),
    ('Finance Consultant'),
    ('Finance Manager'),
    ('Group Financial Controller'),
    ('Payroll Trainee'),
    ('Payroll Associate'),
    ('Payroll Senior Associate'),
    ('Payroll Consultant'),
    ('Payroll Manager'),
    ('Head of Business Services Support'),
    ('Business Services Support Manager'),
    ('Business Services Support Consultant'),
    ('Senior Business Services Support Associate'),
    ('Business Services Support Associate'),
    ('Business Services Support Trainee'),
    ('Head of Property'),
    ('Property Manager'),
    ('Property Team Lead'),
    ('Head of Travel'),
    ('Travel Manager'),
    ('Travel Team Lead'),
    ('Head of Social Responsibility'),
    ('Social Responsibility Manager'),
    ('Education and Partnerships Lead'),
    ('Environmental Sustainability Lead'),
    ('Outreach and Engagement Senior Associate');

